name: CI
on: [push]
jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run PHPStan in dev container
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/aminevg/pingcrm-hybridly-gha
          runCmd: vendor/bin/phpstan
