name: CI
on: [push]
jobs:
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: lorisleiva/laravel-docker:8.2

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: Cache Composer dependencies
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
      - name: Install Composer dependencies
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress
      - name: Copy environment file
        run: cp .env.example .env
      - name: Run PHPStan
        run: vendor/bin/phpstan --memory-limit=1G

  pestphp:
    runs-on: ubuntu-latest
    container:
      image: lorisleiva/laravel-docker:8.2

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: Cache Composer dependencies
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
      - name: Install Composer dependencies
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress
      - name: Copy environment file
        run: cp .env.example .env
      - name: Generate Laravel key
        run: php artisan key:generate
      - name: Run Pest tests
        run: php artisan test

  vitest:
    runs-on: ubuntu-latest
    container:
      image: lorisleiva/laravel-docker:8.2

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: Cache Node dependencies
        id: cache-node
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install Node dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install -g pnpm && pnpm install
      - name: Run vitest tests
        run: npm run test
